name: Python Package Publish

on:
  pull_request:
    branches: 
      - pypi
    types: [closed]

permissions:
    contents: read

jobs:
  build_package:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
          target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter --manifest-path pypdf_seekers/Cargo.toml
          sccache: 'true'
          manylinux: auto
      
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
  
  publish_to_pypi:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
        
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --non-interactive --skip-existing *
